apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwqjqj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwqjqj
  template:
    metadata:
      labels:
        app: qwqjqj
    spec:
      containers:
      - image: okteto.dev/qwqjqj:latest
        name: qwqjqj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "40d6a351-2bcb-4202-a72a-875c4cc481e7"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "ee820f0d-7ff5-4e3f-9d55-2e42db21f25f"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
